// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyClCl6n8U7i5ne-E7CAa6duLLXrhxbX6FY',
    appId: '1:310419058390:android:6147a9822c08c142a02377',
    messagingSenderId: '310419058390',
    projectId: 'loludo-flutter',
    databaseURL: 'https://loludo-flutter-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'loludo-flutter.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB9elJQ_G_d3ytxCBnQr0M-Pth4Df9qT7k',
    appId: '1:310419058390:ios:d54fb0c12bad3556a02377',
    messagingSenderId: '310419058390',
    projectId: 'loludo-flutter',
    databaseURL: 'https://loludo-flutter-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'loludo-flutter.firebasestorage.app',
    iosBundleId: 'com.example.ludoGame',
  );

}